version: "3.8"

services:
  app:
    build: .
    container_name: clinical_notes_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.7.6-standalone
    restart: always
    depends_on:
      - postgres
    container_name: adminer
    ports:
      - "8080:8080"
  
  test:
    build: .
    command: pytest
    volumes:
      - .:/app
    depends_on:
      - app

volumes:
  postgres_data: